### PR TITLE
Update Units.csv

### PR DESCRIPTION
**Pull request by mrichwin**
Added N*cm, N*mm

### CODE REVIEW

**Comment by objorke** [comment]
I updated the generated code ("Run custom tool" on CodeGenerator.tt) and updated the change log and contributors files.

**Comment by mrichwin** [comment]
Ok, thanks. Should that have been my job? (I am kind of new to this...)

**Comment by objorke** [comment]
It should probably be done during build. I will add an issue!

**Comment by objorke** [comment]
#37

**Comment by mrichwin** [comment]
Yes, I had to run the generator as well manually. My concern was whether I should have been responsible for adding that generated file (Torque.cs?) to my branch as well and if I should have modified the change log etc.

**Pull request merged**
