### PR TITLE
More hydrology units

### PR DESCRIPTION
**Pull request by ksheffer-opti**
Add VolumetricWaterContent, MassConcentrationInWater, PrecipitationIntensity, TemperatureChange

### CODE REVIEW

**Comment by ksheffer-opti** [comment]
Closing this PR while I fix a bug. Will resubmit...

**Comment by objorke** [comment]
I agree kelvin should not be degrees. I renamed the units in Temperatur and TemperatureDifference #30.

**Comment by ksheffer-opti** [comment]
Reopening after fixing some conversion factors

**Comment by ksheffer-opti** [comment]
Thanks for the merge. That wraps up the units needed for my current project, but if I have time I'll add a few more of the Concentration quantities.

**Pull request merged**
